server:
  port: 8080
  env: local
  stage: local
  debug: true

websocket:
  endpoint: https://xxx.execute-api.us-east-1.amazonaws.com/local

aws:
  region: us-east-1

database:
  driver: postgres
  uri: postgres://user:password@localhost:5432/dbname
